declare module '@element-plus/icons-vue' {
  import type { DefineComponent } from 'vue'

  type IconComponent = DefineComponent<{}, {}, any>

  export const AddLocation: IconComponent
  export const Aim: IconComponent
  export const AlarmClock: IconComponent
  export const Apple: IconComponent
  export const ArrowDown: IconComponent
  export const ArrowDownBold: IconComponent
  export const ArrowLeft: IconComponent
  export const ArrowLeftBold: IconComponent
  export const ArrowRight: IconComponent
  export const ArrowRightBold: IconComponent
  export const ArrowUp: IconComponent
  export const ArrowUpBold: IconComponent
  export const Avatar: IconComponent
  export const Back: IconComponent
  export const Baseball: IconComponent
  export const Basketball: IconComponent
  export const Bell: IconComponent
  export const BellFilled: IconComponent
  export const Bicycle: IconComponent
  export const Bottom: IconComponent
  export const BottomLeft: IconComponent
  export const BottomRight: IconComponent
  export const Bowl: IconComponent
  export const Box: IconComponent
  export const Briefcase: IconComponent
  export const Brush: IconComponent
  export const BrushFilled: IconComponent
  export const Burger: IconComponent
  export const Calendar: IconComponent
  export const Camera: IconComponent
  export const CameraFilled: IconComponent
  export const CaretBottom: IconComponent
  export const CaretLeft: IconComponent
  export const CaretRight: IconComponent
  export const CaretTop: IconComponent
  export const Cellphone: IconComponent
  export const ChatDotRound: IconComponent
  export const ChatDotSquare: IconComponent
  export const ChatLineRound: IconComponent
  export const ChatLineSquare: IconComponent
  export const ChatRound: IconComponent
  export const ChatSquare: IconComponent
  export const Check: IconComponent
  export const Checked: IconComponent
  export const Cherry: IconComponent
  export const Chicken: IconComponent
  export const ChromeFilled: IconComponent
  export const CircleCheck: IconComponent
  export const CircleCheckFilled: IconComponent
  export const CircleClose: IconComponent
  export const CircleCloseFilled: IconComponent
  export const CirclePlus: IconComponent
  export const CirclePlusFilled: IconComponent
  export const Clock: IconComponent
  export const Close: IconComponent
  export const CloseBold: IconComponent
  export const Cloudy: IconComponent
  export const Coffee: IconComponent
  export const CoffeeCup: IconComponent
  export const Coin: IconComponent
  export const ColdDrink: IconComponent
  export const Collection: IconComponent
  export const CollectionTag: IconComponent
  export const Comment: IconComponent
  export const Compass: IconComponent
  export const Connection: IconComponent
  export const Coordinate: IconComponent
  export const CopyDocument: IconComponent
  export const Cpu: IconComponent
  export const CreditCard: IconComponent
  export const Crop: IconComponent
  export const DArrowLeft: IconComponent
  export const DArrowRight: IconComponent
  export const DCaret: IconComponent
  export const DataAnalysis: IconComponent
  export const DataBoard: IconComponent
  export const DataLine: IconComponent
  export const Delete: IconComponent
  export const DeleteFilled: IconComponent
  export const DeleteLocation: IconComponent
  export const Dessert: IconComponent
  export const Discount: IconComponent
  export const Dish: IconComponent
  export const DishDot: IconComponent
  export const Document: IconComponent
  export const DocumentAdd: IconComponent
  export const DocumentChecked: IconComponent
  export const DocumentCopy: IconComponent
  export const DocumentDelete: IconComponent
  export const DocumentRemove: IconComponent
  export const Download: IconComponent
  export const Drizzling: IconComponent
  export const Edit: IconComponent
  export const EditPen: IconComponent
  export const Eleme: IconComponent
  export const ElemeFilled: IconComponent
  export const ElementPlus: IconComponent
  export const Expand: IconComponent
  export const Failed: IconComponent
  export const Female: IconComponent
  export const Files: IconComponent
  export const Film: IconComponent
  export const Filter: IconComponent
  export const Finished: IconComponent
  export const FirstAidKit: IconComponent
  export const Flag: IconComponent
  export const Fold: IconComponent
  export const Folder: IconComponent
  export const FolderAdd: IconComponent
  export const FolderChecked: IconComponent
  export const FolderDelete: IconComponent
  export const FolderOpened: IconComponent
  export const FolderRemove: IconComponent
  export const Food: IconComponent
  export const Football: IconComponent
  export const ForkSpoon: IconComponent
  export const Fries: IconComponent
  export const FullScreen: IconComponent
  export const Goblet: IconComponent
  export const GobletFull: IconComponent
  export const GobletSquare: IconComponent
  export const GobletSquareFull: IconComponent
  export const GoldMedal: IconComponent
  export const Goods: IconComponent
  export const GoodsFilled: IconComponent
  export const Grape: IconComponent
  export const Grid: IconComponent
  export const Guide: IconComponent
  export const Handbag: IconComponent
  export const Headset: IconComponent
  export const Help: IconComponent
  export const HelpFilled: IconComponent
  export const Hide: IconComponent
  export const Histogram: IconComponent
  export const HomeFilled: IconComponent
  export const HotWater: IconComponent
  export const House: IconComponent
  export const IceCream: IconComponent
  export const IceCreamRound: IconComponent
  export const IceCreamSquare: IconComponent
  export const IceDrink: IconComponent
  export const IceTea: IconComponent
  export const InfoFilled: IconComponent
  export const Iphone: IconComponent
  export const Key: IconComponent
  export const KnifeFork: IconComponent
  export const Lightning: IconComponent
  export const Link: IconComponent
  export const List: IconComponent
  export const Loading: IconComponent
  export const Location: IconComponent
  export const LocationFilled: IconComponent
  export const LocationInformation: IconComponent
  export const Lock: IconComponent
  export const Lollipop: IconComponent
  export const MagicStick: IconComponent
  export const Magnet: IconComponent
  export const Male: IconComponent
  export const Management: IconComponent
  export const MapLocation: IconComponent
  export const Medal: IconComponent
  export const Memo: IconComponent
  export const Menu: IconComponent
  export const Message: IconComponent
  export const MessageBox: IconComponent
  export const Mic: IconComponent
  export const Microphone: IconComponent
  export const MilkTea: IconComponent
  export const Minus: IconComponent
  export const Money: IconComponent
  export const Monitor: IconComponent
  export const Moon: IconComponent
  export const MoonNight: IconComponent
  export const More: IconComponent
  export const MoreFilled: IconComponent
  export const MostlyCloudy: IconComponent
  export const Mouse: IconComponent
  export const Mug: IconComponent
  export const Mute: IconComponent
  export const MuteNotification: IconComponent
  export const NoSmoking: IconComponent
  export const Notebook: IconComponent
  export const Notification: IconComponent
  export const Odometer: IconComponent
  export const OfficeBuilding: IconComponent
  export const Open: IconComponent
  export const Operation: IconComponent
  export const Opportunity: IconComponent
  export const Orange: IconComponent
  export const Paperclip: IconComponent
  export const PartlyCloudy: IconComponent
  export const Pear: IconComponent
  export const Phone: IconComponent
  export const PhoneFilled: IconComponent
  export const Picture: IconComponent
  export const PictureFilled: IconComponent
  export const PictureRounded: IconComponent
  export const PieChart: IconComponent
  export const Place: IconComponent
  export const Platform: IconComponent
  export const Plus: IconComponent
  export const Pointer: IconComponent
  export const Position: IconComponent
  export const Postcard: IconComponent
  export const Pouring: IconComponent
  export const Present: IconComponent
  export const PriceTag: IconComponent
  export const Printer: IconComponent
  export const Promotion: IconComponent
  export const QuartzWatch: IconComponent
  export const QuestionFilled: IconComponent
  export const Rank: IconComponent
  export const Reading: IconComponent
  export const ReadingLamp: IconComponent
  export const Refresh: IconComponent
  export const RefreshLeft: IconComponent
  export const RefreshRight: IconComponent
  export const Refrigerator: IconComponent
  export const Remove: IconComponent
  export const RemoveFilled: IconComponent
  export const Right: IconComponent
  export const ScaleToOriginal: IconComponent
  export const School: IconComponent
  export const Scissor: IconComponent
  export const Search: IconComponent
  export const Select: IconComponent
  export const Sell: IconComponent
  export const SemiSelect: IconComponent
  export const Service: IconComponent
  export const SetUp: IconComponent
  export const Setting: IconComponent
  export const Share: IconComponent
  export const Ship: IconComponent
  export const Shop: IconComponent
  export const ShoppingBag: IconComponent
  export const ShoppingCart: IconComponent
  export const ShoppingCartFull: IconComponent
  export const ShoppingTrolley: IconComponent
  export const Smoking: IconComponent
  export const Soccer: IconComponent
  export const SoldOut: IconComponent
  export const Sort: IconComponent
  export const SortDown: IconComponent
  export const SortUp: IconComponent
  export const Stamp: IconComponent
  export const Star: IconComponent
  export const StarFilled: IconComponent
  export const Stopwatch: IconComponent
  export const SuccessFilled: IconComponent
  export const Sugar: IconComponent
  export const Suitcase: IconComponent
  export const SuitcaseLine: IconComponent
  export const Sunny: IconComponent
  export const Sunrise: IconComponent
  export const Sunset: IconComponent
  export const Switch: IconComponent
  export const SwitchButton: IconComponent
  export const SwitchFilled: IconComponent
  export const TakeawayBox: IconComponent
  export const Ticket: IconComponent
  export const Tickets: IconComponent
  export const Timer: IconComponent
  export const ToiletPaper: IconComponent
  export const Tools: IconComponent
  export const Top: IconComponent
  export const TopLeft: IconComponent
  export const TopRight: IconComponent
  export const TrendCharts: IconComponent
  export const Trophy: IconComponent
  export const TrophyBase: IconComponent
  export const TurnOff: IconComponent
  export const Umbrella: IconComponent
  export const Unlock: IconComponent
  export const Upload: IconComponent
  export const UploadFilled: IconComponent
  export const User: IconComponent
  export const UserFilled: IconComponent
  export const Van: IconComponent
  export const VideoCamera: IconComponent
  export const VideoCameraFilled: IconComponent
  export const VideoPause: IconComponent
  export const VideoPlay: IconComponent
  export const View: IconComponent
  export const Wallet: IconComponent
  export const WalletFilled: IconComponent
  export const WarnTriangleFilled: IconComponent
  export const Warning: IconComponent
  export const WarningFilled: IconComponent
  export const Watch: IconComponent
  export const Watermelon: IconComponent
  export const WindPower: IconComponent
  export const ZoomIn: IconComponent
  export const ZoomOut: IconComponent
}
